/** Textos ES/EN — alineados con data/traducciones.json */

export const I18N = {
  es: {
    nav: {
      home: "Inicio",
      calc: "Calculadora",
      trade: "Comparador",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Créditos",
    },
    main: {
      bienvenida: "Calculadora Oficial de Sorcerer TD",
      home_subtitle:
        "Herramienta comunitaria para calcular valores, comparar trades y gestionar unidades con datos actualizados en la nube.",
      list_values_thanks:
        "Valores de referencia proporcionados por el equipo de Sorcerer TD Value List.",
      official_list_link: "Lista oficial de valores (Google Sheets)",
      home_badge: "Herramienta oficial",
      home_tagline: "Valores · Trades · Unidades",
      home_stat_units: "Unidades",
      home_stat_votes: "Votos por unidad",
      home_stat_live: "Datos en vivo",
      open: "Abrir",
      calc_desc: "Suma el valor de tu inventario con soporte para múltiples votos por unidad.",
      trade_desc: "Compara dos ofertas y descubre si el intercambio es justo.",
      scanner_desc: "Escanea capturas de pantalla — disponible pronto.",
      tester_desc: "Zona de pruebas interna del escáner.",
      sidebar_tagline: "Calculadora oficial",
    },
    sort: {
      label: "Ordenar",
      rarity_desc: "Rareza (mayor primero)",
      rarity_asc: "Rareza (menor primero)",
      name: "Nombre A–Z",
      value_desc: "Valor (mayor primero)",
    },
    scanner: {
      kicker: "SORCERER CALCULATOR",
      title: "Scanner",
      coming: "Próximamente",
      wip: "En construcción",
      live_build: "Obra en curso",
      countdown_target: "Viernes 15 may 2026 · 20:00 (hora peninsular)",
      countdown_heading: "Cuenta atrás",
      countdown_done: "¡Llegó la hora!",
      cd_days: "Días",
      cd_hours: "Horas",
      cd_minutes: "Min",
      cd_seconds: "Seg",
      tester_title: "Modo Tester",
      tester_desc:
        "Acceso temporal para pruebas. Luego se moverá al Scanner final.",
      user: "Usuario",
      password: "Contraseña",
      login: "Entrar",
      login_error: "Credenciales incorrectas.",
      ip_denied: "Acceso restringido. Esta sección solo está disponible desde redes autorizadas.",
      ip_checking: "Verificando acceso…",
      drop_hint:
        "Sube una captura o pégala con Ctrl+V para buscar similitud con unidades.",
      analyze: "Analizar imagen",
      clear: "Limpiar",
      source_loaded: "Imagen cargada",
      no_image: "Primero sube o pega una imagen.",
      analyzing: "Analizando imagen...",
      no_matches: "No se detectaron coincidencias claras.",
      results_title: "Unidades detectadas (beta)",
      total: "Valor total estimado",
      confidence: "Similitud",
    },
    calc: {
      title: "Calculadora de valor",
      subtitle: "Selecciona unidades y ajusta votos para obtener el valor total.",
      search: "Buscar unidad…",
      total: "Valor total",
      clear_all: "Limpiar todo",
      reopen: "Elegir votos…",
      close: "Cerrar",
    },
    trade: {
      title: "Comparador de trade",
      subtitle: "Añade unidades a cada lado y compara el valor total del intercambio.",
      search: "Buscar…",
      clear: "Limpiar todo",
      didactic_intro:
        "Sección para calcular rápidamente los intercambios",
      stock_you: "Tu inventario en el trade",
      stock_opponent: "Inventario del rival",
      stock_empty:
        "",
      picker_caption: "Unidades disponibles · + / −",
      left: "Tu oferta",
      right: "Oferta rival",
      left_tot: "Total izquierda",
      right_tot: "Total derecha",
      diff: "Diferencia",
      fair: "Equilibrado",
      win_left: "Gana izquierda",
      win_right: "Gana derecha",
      modal_title: "Votos por unidad",
      side_left: "(izquierda)",
      side_right: "(derecha)",
      value: "Valor",
    },
    credits: {
      title: "CRÉDITOS",
      subtitle: "Equipo y perfiles oficiales",
      badge: "Sorcerer TD Community",
      foot: "Si quieres aparecer aquí debes colaborar con nosotros",
      role_creator: "Creador del proyecto",
      role_idea_db: "Idea y base de datos",
      open_discord: "Abrir Discord",
      open_roblox: "Abrir Roblox",
      hecho_por: "Hecho por: @meliodas_000.",
      idea: "Idea propuesta por: @Toropapita",
      database: "Base de datos: @Toropapita",
    },
  },
  en: {
    nav: {
      home: "Home",
      calc: "Calculator",
      trade: "Trade",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Credits",
    },
    main: {
      bienvenida: "Official Sorcerer TD Calculator",
      home_subtitle:
        "Community tool to calculate values, compare trades, and manage units with live cloud data.",
      list_values_thanks:
        "Reference values provided by the Sorcerer TD Value List team.",
      official_list_link: "Official value list (Google Sheets)",
      home_badge: "Official tool",
      home_tagline: "Values · Trades · Units",
      home_stat_units: "Units",
      home_stat_votes: "Votes per unit",
      home_stat_live: "Live data",
      open: "Open",
      calc_desc: "Sum your inventory value with support for multiple votes per unit.",
      trade_desc: "Compare two offers and see if the trade is fair.",
      scanner_desc: "Scan screenshots — coming soon.",
      tester_desc: "Internal scanner testing area.",
      sidebar_tagline: "Official calculator",
    },
    sort: {
      label: "Sort",
      rarity_desc: "Rarity (highest first)",
      rarity_asc: "Rarity (lowest first)",
      name: "Name A–Z",
      value_desc: "Value (highest first)",
    },
    scanner: {
      kicker: "SORCERER CALCULATOR",
      title: "Scanner",
      coming: "Coming soon",
      wip: "Under construction",
      live_build: "Work in progress",
      countdown_target: "Friday May 15, 2026 · 8:00 PM (Spain mainland)",
      countdown_heading: "Countdown",
      countdown_done: "It's time!",
      cd_days: "Days",
      cd_hours: "Hours",
      cd_minutes: "Min",
      cd_seconds: "Sec",
      tester_title: "Tester mode",
      tester_desc:
        "Temporary access for testing. It will move to the final Scanner later.",
      user: "User",
      password: "Password",
      login: "Sign in",
      login_error: "Wrong credentials.",
      ip_denied: "Access restricted. This section is only available from authorized networks.",
      ip_checking: "Checking access…",
      drop_hint:
        "Upload a screenshot or paste it with Ctrl+V to match unit images.",
      analyze: "Analyze image",
      clear: "Clear",
      source_loaded: "Image loaded",
      no_image: "Upload or paste an image first.",
      analyzing: "Analyzing image...",
      no_matches: "No clear matches found.",
      results_title: "Detected units (beta)",
      total: "Estimated total value",
      confidence: "Similarity",
    },
    calc: {
      title: "Value calculator",
      subtitle: "Select units and adjust votes to get the total value.",
      search: "Search unit…",
      total: "Total value",
      clear_all: "Clear all",
      reopen: "Choose votes…",
      close: "Close",
    },
    trade: {
      title: "Trade comparison",
      subtitle: "Add units to each side and compare the total trade value.",
      search: "Search…",
      clear: "Clear all",
      didactic_intro:
        "Section for quickly calculating exchanges",
      stock_you: "Your inventory in this trade",
      stock_opponent: "Opponent’s inventory",
      stock_empty:
        "",
      picker_caption: "Available units · + / −",
      left: "Your offer",
      right: "Opponent offer",
      left_tot: "Left total",
      right_tot: "Right total",
      diff: "Difference",
      fair: "Fair",
      win_left: "Left wins",
      win_right: "Right wins",
      modal_title: "Votes per unit",
      side_left: "(left)",
      side_right: "(right)",
      value: "Value",
    },
    credits: {
      title: "CREDITS",
      subtitle: "Team and official profiles",
      badge: "Sorcerer TD Community",
      foot: "If you want to appear here, you must collaborate with us.",
      role_creator: "Project creator",
      role_idea_db: "Idea and database",
      open_discord: "Open Discord",
      open_roblox: "Open Roblox",
      hecho_por: "Made by: @meliodas_000.",
      idea: "Idea proposed by: @Toropapita",
      database: "Database: @Toropapita",
    },
  },
};

export function t(lang, path) {
  const parts = path.split(".");
  let cur = I18N[lang] ?? I18N.es;
  for (const p of parts) cur = cur?.[p];
  return typeof cur === "string" ? cur : path;
}
