/** Textos ES/EN — alineados con data/traducciones.json */

export const I18N = {
  es: {
    nav: {
      home: "Inicio",
      calc: "Calculadora",
      trade: "Comparador",
      values: "Tabla de valores",
      predictions: "Predictions",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Créditos",
    },
    main: {
      bienvenida: "Calculadora Fan-Made de Sorcerer TD",
      home_subtitle:
        "Herramienta hecha por fans para calcular valores, comparar trades y consultar la base de datos de unidades.",
      home_fanmade_notice:
        "Esta web NO es oficial del juego. Es un proyecto fan-made creado por @meliodas_000, sin afiliación con los desarrolladores de Sorcerer TD.",
      list_values_thanks:
        "Los valores de referencia provienen del equipo de Sorcerer TD Value List.",
      official_list_link: "Lista de referencia (Google Sheets)",
      home_badge: "Fan-made",
      home_tagline: "Valores · Trades · Unidades",
      home_stat_units: "Unidades",
      home_stat_votes: "Votos por unidad",
      home_stat_live: "Datos en vivo",
      open: "Abrir",
      calc_desc: "Suma el valor de tu inventario con soporte para múltiples votos por unidad.",
      trade_desc: "Compara dos ofertas y descubre si el intercambio es justo.",
      values_desc: "Consulta el valor base de cada unidad y los valores por tipo de voto.",
      predictions_desc: "Tendencias experimentales: qué unidades podrían subir o bajar tras cambios de balance.",
      scanner_desc: "Escanea capturas de pantalla — disponible pronto.",
      tester_desc: "Zona de pruebas interna del escáner.",
      sidebar_tagline: "Proyecto fan-made",
    },
    sort: {
      label: "Ordenar",
      rarity_desc: "Rareza (mayor primero)",
      rarity_asc: "Rareza (menor primero)",
      name: "Nombre A–Z",
      value_desc: "Valor (mayor primero)",
    },
    filter: {
      rarity_label: "Rareza",
      all: "Todas",
    },
    votes: {
      v1: "Sin voto",
      v2: "Fuerza",
      v3: "Velocidad",
      v4: "Alcance",
      v5: "Summoner",
      v6: "Fortuna",
      v7: "Poder",
      v8: "Rápido",
      v9: "Caster 1",
      v10: "Eficiencia",
      v11: "Restricción celestial",
      v12: "Honored One",
      v13: "Caster 2",
    },
    scanner: {
      kicker: "SORCERER CALCULATOR",
      title: "Scanner",
      coming: "Próximamente",
      wip: "En construcción",
      live_build: "Obra en curso",
      countdown_target: "Viernes 15 may 2026 · 20:00 (hora peninsular)",
      countdown_heading: "Cuenta atrás",
      countdown_done: "¡Llegó la hora!",
      cd_days: "Días",
      cd_hours: "Horas",
      cd_minutes: "Min",
      cd_seconds: "Seg",
      tester_title: "Modo Tester",
      tester_desc:
        "Acceso temporal para pruebas. Luego se moverá al Scanner final.",
      user: "Usuario",
      password: "Contraseña",
      login: "Entrar",
      login_error: "Credenciales incorrectas.",
      ip_denied: "Acceso restringido. Esta sección solo está disponible desde redes autorizadas.",
      ip_checking: "Verificando acceso…",
      drop_hint:
        "Sube una captura o pégala con Ctrl+V para buscar similitud con unidades.",
      analyze: "Analizar imagen",
      clear: "Limpiar",
      source_loaded: "Imagen cargada",
      no_image: "Primero sube o pega una imagen.",
      analyzing: "Analizando imagen...",
      error: "Error en el análisis visual: ",
      no_matches: "No se detectaron coincidencias claras.",
      top5_title: "Top 5 candidatos visuales",
      results_title: "Unidades detectadas",
      total: "Valor total estimado",
      confidence: "Similitud",
    },
    calc: {
      title: "Calculadora de valor",
      subtitle: "Selecciona unidades y ajusta votos para obtener el valor total.",
      search: "Buscar unidad…",
      total: "Valor total",
      clear_all: "Limpiar todo",
      reopen: "Elegir votos…",
      close: "Cerrar",
    },
    trade: {
      title: "Comparador de trade",
      subtitle: "Añade unidades a cada lado y compara el valor total del intercambio.",
      search: "Buscar…",
      clear: "Limpiar todo",
      didactic_intro:
        "Sección para calcular rápidamente los intercambios",
      stock_you: "Tu inventario en el trade",
      stock_opponent: "Inventario del rival",
      stock_empty:
        "",
      picker_caption: "Unidades disponibles",
      inventory_caption: "Inventario del trade",
      left: "Tu oferta",
      right: "Oferta rival",
      left_tot: "Total izquierda",
      right_tot: "Total derecha",
      diff: "Diferencia",
      fair: "Equilibrado",
      win_left: "Gana izquierda",
      win_right: "Gana derecha",
      left_short: "Tú",
      right_short: "Rival",
      bar_empty: "Añade unidades para comparar",
      modal_title: "Votos por unidad",
      side_left: "(izquierda)",
      side_right: "(derecha)",
      value: "Valor",
      suggest_toggle: "Sugerencias inteligentes",
      suggest_hide: "Ocultar sugerencias",
      suggest_need_more:
        "Te faltan {gap} pts para igualar la oferta rival.",
      suggest_fair: "El trade ya está equilibrado.",
      suggest_winning: "Vas ganando por {gap} pts.",
      suggest_empty_right:
        "Añade unidades en la oferta rival para analizar el trade.",
      suggest_receive: "Recibes unidades con demanda media {dem}/10.",
      suggest_add:
        "Añade {name} (+{val}) — quedarías a {remain} pts del rival",
      suggest_add_pair:
        "Añade {name1} + {name2} (+{val}) — quedarías a {remain} pts del rival",
      suggest_worth: "Demanda {dem}/10 · {stability}",
      suggest_apply: "Añadir",
      suggest_best: "Mejor opción",
      suggest_rank: "Opción #{n}",
      suggest_match: "{pct}% coincidencia",
      suggest_pts_short: "Faltan {remain} pts",
      inventory_open: "Mi inventario del juego",
      inventory_title: "Unidades que tienes",
      inventory_hint:
        "Marca las unidades de tu inventario para recibir recomendaciones personalizadas.",
      inventory_save: "Guardar inventario",
      inventory_clear: "Limpiar selección",
      inventory_search: "Buscar unidad…",
      inventory_count: "{n} unidades seleccionadas",
      suggest_from_owned: "Sugerencias según tu inventario ({n} unidades)",
      suggest_no_owned:
        "Ninguna unidad marcada encaja con el gap. Añade más en «Mi inventario del juego».",
    },
    demand: {
      fair: "Valor justo",
      overpay: "Overpay",
      underpay: "Underpay",
      unknown: "Sin datos",
      margin: "margen est.",
      demand_score: "Demanda",
      stability_stable: "Estable",
      stability_dropping: "Bajando",
      stability_fluctuating: "Fluctuando",
      hint_fair: "Se tradea cerca del valor base de la lista.",
      hint_overpay: "Suele recibir ofertas por encima del valor base.",
      hint_underpay: "Suele recibir ofertas por debajo del valor base.",
      hint_unknown: "Aún no hay nota de demanda en la base de datos.",
    },
    values: {
      title: "Tabla de valores",
      subtitle:
        "Referencia completa de unidades, rarezas y valores por voto según la base de datos actual.",
      search: "Buscar unidad…",
      units_heading: "Unidades y valor base",
      votes_heading: "Valores por voto",
      votes_hint:
        "Solo votos que cambian el valor de cada unidad. HR y THO siempre visibles.",
      col_unit: "Unidad",
      col_rarity: "Rareza",
      col_base: "Valor base",
      col_demand: "Demanda",
      col_market: "Mercado",
      col_stability: "Estabilidad",
      col_votes: "Votos compatibles",
      no_results: "No hay unidades que coincidan con el filtro.",
    },
    predictions: {
      title: "Predictions",
      subtitle:
        "Señales experimentales para tradear o holdear según cambios en la lista de valores.",
      beta_badge: "BETA · Experimental",
      beta_notice:
        "Esta sección es experimental y puede eliminarse. No es consejo financiero: usa la lista oficial como referencia final.",
      summary_up: "Al alza",
      summary_stable: "Estables",
      summary_down: "A la baja",
      history_ready:
        "Comparamos con snapshots locales cuando la lista de valores cambia en Supabase.",
      history_warming:
        "Aún recopilando historial. Vuelve tras un cambio de balance en la lista para ver deltas reales.",
      filter_all: "Todas",
      filter_up: "Subiendo",
      filter_down: "Bajando",
      filter_stable: "Estables",
      no_results: "Ninguna unidad coincide con este filtro.",
      base_value: "Valor base",
      vote_label: "Voto Fuerza",
      vote13_label: "Voto C2",
      trend_up: "Subió",
      trend_down: "Bajó",
      trend_stable: "Estable",
      trend_forecast_up: "Posible subida",
      trend_forecast_down: "Posible bajada",
      tip_trade: "Buen momento para tradear si buscas valor actual.",
      tip_hold: "Podría compensarse pronto — considera holdear.",
      tip_stable: "Sin cambios recientes detectados.",
      tip_caution: "Valor alto vs su tier — cuidado al tradear ahora.",
      sort_label: "Ordenar por",
      sort_score: "Señal (recomendado)",
      sort_rarity: "Rareza (agrupado)",
      sort_delta: "Mayor cambio",
      sort_value: "Valor base",
      sort_name: "Nombre A–Z",
      chart_units: "unidades",
      chart_by_rarity: "Tendencias por rareza",
      chart_no_data: "Sin datos suficientes.",
      score_hint: "Puntuación compuesta: subidas/bajadas + votos.",
      showing_count: "Mostrando {shown} de {total} unidades",
      section_count: "{count} unidades",
    },
    credits: {
      title: "CRÉDITOS",
      kicker: "Hall of Fame",
      subtitle: "Equipo y perfiles oficiales",
      badge: "Sorcerer TD Community",
      foot: "Si quieres aparecer aquí debes colaborar con nosotros",
      role_creator: "Creador del proyecto y programador principal",
      role_idea_db: "Idea, base de datos, tester y cofundador",
      role_tester_ideas: "Tester e ideas",
      open_discord: "Abrir Discord",
      open_roblox: "Abrir Roblox",
      hecho_por: "Hecho por: @meliodas_000.",
      idea: "Idea propuesta por: @Toropapita",
      database: "Base de datos: @Toropapita",
    },
  },
  en: {
    nav: {
      home: "Home",
      calc: "Calculator",
      trade: "Trade",
      values: "Value tables",
      predictions: "Predictions",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Credits",
    },
    main: {
      bienvenida: "Fan-Made Sorcerer TD Calculator",
      home_subtitle:
        "A fan-made tool to calculate values, compare trades, and browse the unit database.",
      home_fanmade_notice:
        "This site is NOT official. It is a fan-made project by @meliodas_000, not affiliated with Sorcerer TD developers.",
      list_values_thanks:
        "Reference values come from the Sorcerer TD Value List team.",
      official_list_link: "Reference spreadsheet (Google Sheets)",
      home_badge: "Fan-made",
      home_tagline: "Values · Trades · Units",
      home_stat_units: "Units",
      home_stat_votes: "Votes per unit",
      home_stat_live: "Live data",
      open: "Open",
      calc_desc: "Sum your inventory value with support for multiple votes per unit.",
      trade_desc: "Compare two offers and see if the trade is fair.",
      values_desc: "Look up each unit’s base value and per-vote values.",
      predictions_desc: "Experimental trends: units that may rise or fall after balance changes.",
      scanner_desc: "Scan screenshots — coming soon.",
      tester_desc: "Internal scanner testing area.",
      sidebar_tagline: "Fan-made project",
    },
    sort: {
      label: "Sort",
      rarity_desc: "Rarity (highest first)",
      rarity_asc: "Rarity (lowest first)",
      name: "Name A–Z",
      value_desc: "Value (highest first)",
    },
    filter: {
      rarity_label: "Rarity",
      all: "All",
    },
    votes: {
      v1: "No vote",
      v2: "Strength",
      v3: "Speed",
      v4: "Range",
      v5: "Summoner",
      v6: "Fortune",
      v7: "Power",
      v8: "Rapid",
      v9: "Caster 1",
      v10: "Efficiency",
      v11: "Heavenly restriction",
      v12: "Honored One",
      v13: "Caster 2",
    },
    scanner: {
      kicker: "SORCERER CALCULATOR",
      title: "Scanner",
      coming: "Coming soon",
      wip: "Under construction",
      live_build: "Work in progress",
      countdown_target: "Friday May 15, 2026 · 8:00 PM (Spain mainland)",
      countdown_heading: "Countdown",
      countdown_done: "It's time!",
      cd_days: "Days",
      cd_hours: "Hours",
      cd_minutes: "Min",
      cd_seconds: "Sec",
      tester_title: "Tester mode",
      tester_desc:
        "Temporary access for testing. It will move to the final Scanner later.",
      user: "User",
      password: "Password",
      login: "Sign in",
      login_error: "Wrong credentials.",
      ip_denied: "Access restricted. This section is only available from authorized networks.",
      ip_checking: "Checking access…",
      drop_hint:
        "Upload a screenshot or paste it with Ctrl+V to match unit images.",
      analyze: "Analyze image",
      clear: "Clear",
      source_loaded: "Image loaded",
      no_image: "Upload or paste an image first.",
      analyzing: "Analyzing image...",
      error: "Visual analysis error: ",
      no_matches: "No clear matches found.",
      top5_title: "Visual Top 5 candidates",
      results_title: "Detected units",
      total: "Estimated total value",
      confidence: "Similarity",
    },
    calc: {
      title: "Value calculator",
      subtitle: "Select units and adjust votes to get the total value.",
      search: "Search unit…",
      total: "Total value",
      clear_all: "Clear all",
      reopen: "Choose votes…",
      close: "Close",
    },
    trade: {
      title: "Trade comparison",
      subtitle: "Add units to each side and compare the total trade value.",
      search: "Search…",
      clear: "Clear all",
      didactic_intro:
        "Section for quickly calculating exchanges",
      stock_you: "Your inventory in this trade",
      stock_opponent: "Opponent’s inventory",
      stock_empty:
        "",
      picker_caption: "Available units",
      inventory_caption: "Trade inventory",
      left: "Your offer",
      right: "Opponent offer",
      left_tot: "Left total",
      right_tot: "Right total",
      diff: "Difference",
      fair: "Fair",
      win_left: "Left wins",
      win_right: "Right wins",
      left_short: "You",
      right_short: "Them",
      bar_empty: "Add units to compare",
      modal_title: "Votes per unit",
      side_left: "(left)",
      side_right: "(right)",
      value: "Value",
      suggest_toggle: "Smart suggestions",
      suggest_hide: "Hide suggestions",
      suggest_need_more: "You need {gap} more pts to match the opponent offer.",
      suggest_fair: "This trade is already balanced.",
      suggest_winning: "You are ahead by {gap} pts.",
      suggest_empty_right:
        "Add units on the opponent side to analyze this trade.",
      suggest_receive: "You receive units with average demand {dem}/10.",
      suggest_add:
        "Add {name} (+{val}) — you would be {remain} pts short of them",
      suggest_add_pair:
        "Add {name1} + {name2} (+{val}) — you would be {remain} pts short of them",
      suggest_worth: "Demand {dem}/10 · {stability}",
      suggest_apply: "Add",
      suggest_best: "Best pick",
      suggest_rank: "Option #{n}",
      suggest_match: "{pct}% match",
      suggest_pts_short: "{remain} pts short",
      inventory_open: "My in-game inventory",
      inventory_title: "Units you own",
      inventory_hint:
        "Mark units from your inventory to get personalized trade suggestions.",
      inventory_save: "Save inventory",
      inventory_clear: "Clear selection",
      inventory_search: "Search unit…",
      inventory_count: "{n} units selected",
      suggest_from_owned: "Suggestions from your inventory ({n} units)",
      suggest_no_owned:
        "No marked units fit the gap. Add more in «My in-game inventory».",
    },
    demand: {
      fair: "Fair value",
      overpay: "Overpay",
      underpay: "Underpay",
      unknown: "No data",
      margin: "est. margin",
      demand_score: "Demand",
      stability_stable: "Stable",
      stability_dropping: "Dropping",
      stability_fluctuating: "Fluctuating",
      hint_fair: "Usually trades near the list base value.",
      hint_overpay: "Often receives offers above base value.",
      hint_underpay: "Often receives offers below base value.",
      hint_unknown: "No demand score in the database yet.",
    },
    values: {
      title: "Value tables",
      subtitle:
        "Full reference of units, rarities, and per-vote values from the current database.",
      search: "Search unit…",
      units_heading: "Units and base value",
      votes_heading: "Values per vote",
      votes_hint:
        "Only votes that change each unit's value. HR and THO are always shown.",
      col_unit: "Unit",
      col_rarity: "Rarity",
      col_base: "Base value",
      col_demand: "Demand",
      col_market: "Market",
      col_stability: "Stability",
      col_votes: "Compatible votes",
      no_results: "No units match the current filter.",
    },
    predictions: {
      title: "Predictions",
      subtitle:
        "Experimental signals for trading or holding based on value list changes.",
      beta_badge: "BETA · Experimental",
      beta_notice:
        "This section is experimental and may be removed. Not financial advice — always check the official list.",
      summary_up: "Trending up",
      summary_stable: "Stable",
      summary_down: "Trending down",
      history_ready:
        "We compare local snapshots whenever the Supabase value list changes.",
      history_warming:
        "Still building history. Come back after a balance update to see real deltas.",
      filter_all: "All",
      filter_up: "Rising",
      filter_down: "Falling",
      filter_stable: "Stable",
      no_results: "No units match this filter.",
      base_value: "Base value",
      vote_label: "Strength vote",
      vote13_label: "Caster 2 vote",
      trend_up: "Up",
      trend_down: "Down",
      trend_stable: "Stable",
      trend_forecast_up: "May rise",
      trend_forecast_down: "May fall",
      tip_trade: "Good time to trade if you want current value.",
      tip_hold: "May catch up soon — consider holding.",
      tip_stable: "No recent changes detected.",
      tip_caution: "High value for its tier — trade carefully.",
      sort_label: "Sort by",
      sort_score: "Signal (recommended)",
      sort_rarity: "Rarity (grouped)",
      sort_delta: "Largest change",
      sort_value: "Base value",
      sort_name: "Name A–Z",
      chart_units: "units",
      chart_by_rarity: "Trends by rarity",
      chart_no_data: "Not enough data yet.",
      score_hint: "Composite score from trends and votes.",
      showing_count: "Showing {shown} of {total} units",
      section_count: "{count} units",
    },
    credits: {
      title: "CREDITS",
      kicker: "Hall of Fame",
      subtitle: "Team and official profiles",
      badge: "Sorcerer TD Community",
      foot: "If you want to appear here, you must collaborate with us.",
      role_creator: "Project creator and lead developer",
      role_idea_db: "Idea, database, tester and co-founder",
      role_tester_ideas: "Tester & ideas",
      open_discord: "Open Discord",
      open_roblox: "Open Roblox",
      hecho_por: "Made by: @meliodas_000.",
      idea: "Idea proposed by: @Toropapita",
      database: "Database: @Toropapita",
    },
  },
};

export function t(lang, path, vars) {
  const parts = path.split(".");
  let cur = I18N[lang] ?? I18N.es;
  for (const p of parts) cur = cur?.[p];
  let s = typeof cur === "string" ? cur : path;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replaceAll(`{${k}}`, String(v));
    }
  }
  return s;
}
