/** Textos ES/EN — alineados con data/traducciones.json */

export const I18N = {
  es: {
    nav: {
      home: "Inicio",
      calc: "Calculadora",
      trade: "Comparador",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Créditos",
    },
    main: {
      bienvenida: "BIENVENIDO A TD HUB",
      home_subtitle:
        "Usa datos en la nube. Despliegue gratis con GitHub Pages u otro hosting estático.",
      list_values_thanks:
        "Agradecemos al equipo de Sorcerer TD Value List por los valores de referencia que hacen posible esta calculadora.",
      official_list_link: "Documento oficial de la lista (Google Sheets)",
      home_badge: "Versión web",
      open: "Abrir",
      calc_desc: "Calcula valor con varios votos por unidad.",
      trade_desc: "Compara dos ofertas lado a lado.",
      scanner_desc: "Herramienta de escaneo — disponible pronto.",
      tester_desc: "Zona de pruebas del escáner con login temporal.",
    },
    scanner: {
      kicker: "TD HUB",
      title: "Scanner",
      coming: "Próximamente",
      wip: "En construcción",
      live_build: "Obra en curso",
      countdown_target: "Viernes 29 may 2026 · 20:00 (hora peninsular)",
      countdown_heading: "Cuenta atrás",
      countdown_done: "¡Llegó la hora!",
      cd_days: "Días",
      cd_hours: "Horas",
      cd_minutes: "Min",
      cd_seconds: "Seg",
      tester_title: "Modo Tester",
      tester_desc:
        "Acceso temporal para pruebas. Luego se moverá al Scanner final.",
      user: "Usuario",
      password: "Contraseña",
      login: "Entrar",
      login_error: "Credenciales incorrectas.",
      drop_hint:
        "Sube una captura o pégala con Ctrl+V para buscar similitud con unidades.",
      analyze: "Analizar imagen",
      clear: "Limpiar",
      source_loaded: "Imagen cargada",
      no_image: "Primero sube o pega una imagen.",
      analyzing: "Analizando imagen...",
      no_matches: "No se detectaron coincidencias claras.",
      results_title: "Unidades detectadas (beta)",
      total: "Valor total estimado",
      confidence: "Similitud",
    },
    calc: {
      title: "Calculadora de valor",
      search: "Buscar unidad…",
      total: "Valor total",
      clear_all: "Limpiar todo",
      reopen: "Elegir votos…",
      close: "Cerrar",
    },
    trade: {
      title: "Comparador de trade",
      search: "Buscar…",
      clear: "Limpiar todo",
      didactic_intro:
        "Sección para calcular rápidamente los intercambios",
      stock_you: "Tu inventario en el trade",
      stock_opponent: "Inventario del rival",
      stock_empty:
        "",
      picker_caption: "Unidades disponibles · + / −",
      left: "Tu oferta",
      right: "Oferta rival",
      left_tot: "Total izquierda",
      right_tot: "Total derecha",
      diff: "Diferencia",
      fair: "Equilibrado",
      win_left: "Gana izquierda",
      win_right: "Gana derecha",
      modal_title: "Votos por unidad",
      side_left: "(izquierda)",
      side_right: "(derecha)",
      value: "Valor",
    },
    credits: {
      title: "CRÉDITOS",
      subtitle: "Equipo y perfiles oficiales",
      badge: "TD HUB Community",
      foot: "Si quieres aparecer aquí debes colaborar con nosotros",
      role_creator: "Creador del proyecto",
      role_idea_db: "Idea y base de datos",
      open_discord: "Abrir Discord",
      open_roblox: "Abrir Roblox",
      hecho_por: "Hecho por: @meliodas_000.",
      idea: "Idea propuesta por: @Toropapita",
      database: "Base de datos: @Toropapita",
    },
  },
  en: {
    nav: {
      home: "Home",
      calc: "Calculator",
      trade: "Trade",
      scanner: "Scanner",
      tester: "Tester",
      credits: "Credits",
    },
    main: {
      bienvenida: "WELCOME TO TD HUB",
      home_subtitle:
        "Cloud-backed data. Free deploy on GitHub Pages or any static host.",
      list_values_thanks:
        "Thanks to the Sorcerer TD Value List team for the reference values that power this calculator.",
      official_list_link: "Official value list spreadsheet (Google Sheets)",
      home_badge: "Web build",
      open: "Open",
      calc_desc: "Calculate value with multiple votes per unit.",
      trade_desc: "Compare both offers side by side.",
      scanner_desc: "Scanning tool — coming soon.",
      tester_desc: "Scanner testing area with temporary login.",
    },
    scanner: {
      kicker: "TD HUB",
      title: "Scanner",
      coming: "Coming soon",
      wip: "Under construction",
      live_build: "Work in progress",
      countdown_target: "Friday May 29, 2026 · 8:00 PM (Spain mainland)",
      countdown_heading: "Countdown",
      countdown_done: "It's time!",
      cd_days: "Days",
      cd_hours: "Hours",
      cd_minutes: "Min",
      cd_seconds: "Sec",
      tester_title: "Tester mode",
      tester_desc:
        "Temporary access for testing. It will move to the final Scanner later.",
      user: "User",
      password: "Password",
      login: "Sign in",
      login_error: "Wrong credentials.",
      drop_hint:
        "Upload a screenshot or paste it with Ctrl+V to match unit images.",
      analyze: "Analyze image",
      clear: "Clear",
      source_loaded: "Image loaded",
      no_image: "Upload or paste an image first.",
      analyzing: "Analyzing image...",
      no_matches: "No clear matches found.",
      results_title: "Detected units (beta)",
      total: "Estimated total value",
      confidence: "Similarity",
    },
    calc: {
      title: "Value calculator",
      search: "Search unit…",
      total: "Total value",
      clear_all: "Clear all",
      reopen: "Choose votes…",
      close: "Close",
    },
    trade: {
      title: "Trade comparison",
      search: "Search…",
      clear: "Clear all",
      didactic_intro:
        "Section for quickly calculating exchanges",
      stock_you: "Your inventory in this trade",
      stock_opponent: "Opponent’s inventory",
      stock_empty:
        "",
      picker_caption: "Available units · + / −",
      left: "Your offer",
      right: "Opponent offer",
      left_tot: "Left total",
      right_tot: "Right total",
      diff: "Difference",
      fair: "Fair",
      win_left: "Left wins",
      win_right: "Right wins",
      modal_title: "Votes per unit",
      side_left: "(left)",
      side_right: "(right)",
      value: "Value",
    },
    credits: {
      title: "CREDITS",
      subtitle: "Team and official profiles",
      badge: "TD HUB Community",
      foot: "If you want to appear here, you must collaborate with us.",
      role_creator: "Project creator",
      role_idea_db: "Idea and database",
      open_discord: "Open Discord",
      open_roblox: "Open Roblox",
      hecho_por: "Made by: @meliodas_000.",
      idea: "Idea proposed by: @Toropapita",
      database: "Database: @Toropapita",
    },
  },
};

export function t(lang, path) {
  const parts = path.split(".");
  let cur = I18N[lang] ?? I18N.es;
  for (const p of parts) cur = cur?.[p];
  return typeof cur === "string" ? cur : path;
}
